### ISSUE TITLE
ブロックのそれぞれにスペースを設定したい。

### ISSUE THREAD

**Issue by megane9988** [inc2734/unitone#78]
TTT においては、theme.jsonにおいて以下のような設定があり

```
	"settings": {
		"appearanceTools": true,
```

この設定の影響で、右パネルに寸法という
余白の設定が各ブロックでできるようになってます。

この機能があると、テーマ編集においてそれぞれに余白が付けられやすくて良いかと考えました。

**Comment by inc2734** [comment]
これはちょっと悩んでいるところで、そのほうが便利といえば便利なんですけど、Every Layout 的には margin は直接コンポーネントに付与すべきではない（親でコントロールするべき）ということで、Stack ブロックであったり、各ブロックで gap の設定ができるようになっています。

必ず親でのみコントロールされると制限していたほうが（入れ子が深くなったり等面倒ではあるけど）考えることが少なくてわかりやすいのかなぁと思ったりします。
